export * from './HeadingForArticles';
export * from './HeadingForCompany';
export * from './HeadingForFaq';
export * from './HeadingForMyProfile';
export * from './HeadingForNews';
export * from './HeadingForResponses';
export * from './HeadingForResume';
export * from './HeadingForSearchCompany';
export * from './HeadingForVacancy';
