/* eslint-disable @typescript-eslint/no-redeclare */
import type { ValueOf } from 'shared/utils';

export const IconEnum = {
  bell: 'bell',
  bellPush: 'bellPush',
  closeMd: 'closeMd',
  closeSm: 'closeSm',
  down: 'down',
  email: 'email',
  emailPush: 'emailPush',
  left: 'left',
  leftLine: 'leftLine',
  logo: 'logo',
  map: 'map',
  menu: 'menu',
  pensil: 'pensil',
  right: 'right',
  rightLine: 'rightLine',
  search: 'search',
  show: 'show',
  up: 'up',
  google: 'google',
  fb: 'fb',
  arrowLeft: 'arrowLeft',
  arrowRight: 'arrowRight',
  cart: 'cart',
  copy: 'copy',
  verifed: 'verifed',
  chat: 'chat',
  navi: 'navi',
  noteEdit: 'noteEdit',
  noteSearch: 'noteSearch',
  user: 'user',
  view: 'view',
  viewHide: 'viewHide',
  filter: 'filter',
  download: 'download',
  share: 'share',
  attention: 'attention',
  attentionInfo: 'attentionInfo',
  attentionError: 'attentionError',
  attentionStop: 'attentionStop',
  attentionSuccess: 'attentionSuccess',
  attentionNotVerified: 'attentionNotVerified',
  attentionVerified: 'attentionVerified',
  stroke: 'stroke',
  editPencilLine: 'editPencilLine',
  notVerifed: 'notVerifed',
  statusApproved: 'statusApproved',
  statusExpectation: 'statusExpectation',
  statusWarning: 'statusWarning',
  blackCamera: 'blackCamera',
  blackMail: 'blackMail',
  blackWarning: 'blackWarning',
  emojiBriefcase: 'emojiBriefcase',
  emojiDocument: 'emojiDocument',
  emojiFaq: 'emojiFaq',
  emojiShield: 'emojiShield',
  emojiStar: 'emojiStar',
  emojiStar2: 'emojiStar2',
  emojiZzz: 'emojiZzz',
  warning: 'warning',
} as const;

export type IconEnum = ValueOf<typeof IconEnum>;
