/* tslint:disable */
/* eslint-disable */
/**
 * Feeds API
 * Feeds API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from './../../runtime';
import type {
  GetFaq200Response,
  GetFeedsResponse,
} from '../models';

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Returns a faq
     */
    async getFaqRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetFaq200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/faq`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns a faq
     */
    async getFaq(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetFaq200Response> {
        const response = await this.getFaqRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns all feeds
     * Returns all feeds
     */
    async getFeedsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetFeedsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/feeds`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns all feeds
     * Returns all feeds
     */
    async getFeeds(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetFeedsResponse> {
        const response = await this.getFeedsRaw(initOverrides);
        return await response.value();
    }

}
