openapi: "3.0.0"
info:
  version: 1.0.0
  title: Responses API
  description: Responses API
servers:
  - url: http://localhost:8000
  - url: https://api.test.upjob.com
paths:
  /api/v2/files/upload:
    post:
      x-stability-level: "alpha"
      tags:
        - Media
      summary: Upload files to file storage
      operationId: postFilesUpload
      responses:
        "200":
          description: Successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UploadResponse"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                fileName:
                  type: string
                  format: binary
components:
  schemas:
    UploadResponse:
      type: object
      required:
        - url
      properties:
        url:
          type: string
          format: uri
