import type { IPalette } from '~/types/interfaces/iPalette';

import type { ITheme } from '../types/interfaces/iTheme';

export function getTheme(palette: IPalette): ITheme {
  return {
    backgroundColor: palette.neutral.neutral4,
    defaultTextColor: palette.darken.darken1.darken1_base,
    errorTextColor: palette.info.info_errors.info_errors_variant2,
    accentTextColor: palette.accent.accent1.accent1_base,
    blackIconColor: palette.darken.darken1.darken1_base,
    buttons: {
      primary: {
        backgroundColor: palette.accent.accent1.accent1_base,
        focusBackgroundColor: palette.accent.accent2,
        disabledBackgroundColor: palette.darken.darken1.darken1_variant2,
        spanColor: palette.neutral.neutral1,
        iconColor: palette.neutral.neutral1,
        iconColorHover: palette.neutral.neutral1,
        iconDisable: palette.neutral.neutral1,
        shadow: palette.shadow.level_1,
      },
      secondary: {
        backgroundColor: palette.neutral.neutral1,
        focusBackgroundColor: palette.darken.darken1.darken1_variant5,
        activeBackgroundColor: palette.darken.darken1.darken1_variant6,
        disabledBackgroundColor: palette.neutral.none,
        spanColor: palette.darken.darken1.darken1_base,
        focusSpanColor: palette.accent.accent1.accent1_base,
        disabledSpanColor: palette.darken.darken1.darken1_variant2,
        iconColor: palette.accent.accent1.accent1_base,
        iconColorHover: palette.accent.accent1.accent1_base,
        iconDisable: palette.darken.darken1.darken1_variant2,
      },
      tertiary: {
        backgroundColor: palette.neutral.none,
        activeBackgroundColor: palette.darken.darken1.darken1_variant3,
        focusBackgroundColor: palette.darken.darken1.darken1_variant4,
        disabledBackgroundColor: palette.neutral.none,
        spanColor: palette.darken.darken1.darken1_base,
        activeSpanColor: palette.darken.darken1.darken1_base,
        disabledSpanColor: palette.darken.darken1.darken1_variant2,
      },
      chips: {
        backgroundColor: palette.neutral.neutral3,
        focusBackgroundColor: palette.darken.darken1.darken1_variant4,
        activeBackgroundColor: palette.darken.darken1.darken1_variant3,
        spanColor: palette.darken.darken1.darken1_base,
        focusSpanColor: palette.accent.accent1.accent1_base,
        activeBorderColor: palette.accent.accent1.accent1_base,
      },
      small: {
        textColor: palette.accent.accent1.accent1_base,
        backgroundColor: palette.neutral.neutral1,
        borderColor: palette.darken.darken1.darken1_variant1,
        pressedBacgroundColor: palette.darken.darken1.darken1_variant3,
        hoverBackgroundColor: palette.darken.darken1.darken1_variant4,
        hoverBorderColor: palette.darken.darken1.darken1_variant1,
        hoverBorderSpanColor: palette.neutral.neutral1,
        focusBorderColor: palette.darken.darken1.darken1_variant1,
        iconColor: palette.accent.accent1.accent1_base,
        iconColorHover: palette.neutral.neutral1,
        iconDisable: palette.darken.darken2.darken2_variant2,
      },
    },
    switcher: {
      backgroundDefault: palette.darken.darken2.darken2_variant2,
      backgroundChecked: palette.accent.accent1.accent1_base,
      textCheckedColor: palette.neutral.neutral1,
      textDefaultColor: palette.darken.darken2.darken2_base,
      backgroundTogglerColor: palette.neutral.neutral1,
    },
    inputs: {
      borderColor: palette.darken.darken1.darken1_variant1,
      borderFocusColor: palette.accent.accent1.accent1_base,
      backgroundDefaultColor: palette.neutral.neutral2,
    },
    сards: {
      articlesTextColor: palette.darken.darken1.darken1_variant2,
      vacanciesTextColor: palette.accent.accent1.accent1_base,
      noVacanciesTextColor: palette.darken.darken1.darken1_variant2,
      descriptionTextColor: palette.darken.darken1.darken1_variant1,
      imageBackground: palette.neutral.neutral3,
      cardContentBackground: palette.neutral.neutral1,
      shadow: palette.shadow.level_2,
    },
    search: {
      backgroundWrapper: palette.neutral.neutral1,
      svgColor: palette.darken.darken2.darken2_base,
      svgFocusColor: palette.accent.accent1.accent1_base,
      borderColor: palette.darken.darken2.darken2_base,
      middleBorderColor: palette.neutral.neutral4,
      variantSearchCities: palette.darken.darken1.darken1_variant1,
    },
    tabs: {
      middleBorder: {
        backgroundColor: palette.accent.accent1.accent1_base,
      },
      tabButton: {
        activeBackgroundColor: palette.neutral.neutral1,
        backgroundColor: palette.darken.darken2.darken2_variant2,
        focusBackgroundColor: palette.neutral.neutral1,
        focusActiveBackgroundColor: palette.neutral.neutral4,
        focusSpanBackgroundColor: palette.accent.accent1.accent1_base,
        focusSpanActiveBackgroundColor: palette.darken.darken1.darken1_base,
      },
      tabContainer: {
        backgroundColor: palette.darken.darken2.darken2_variant2,
      },
      activeTabColor: palette.darken.darken1.darken1_base,
      disabledTabColor: palette.darken.darken1.darken1_variant1,
    },
    pagination: {
      borderColor: palette.darken.darken1.darken1_variant2,
      activeBorderColor: palette.accent.accent1.accent1_base,
      backgroundActiveColor: palette.accent.accent1.accent1_base,
      backgroundHoverColor: palette.neutral.neutral3,
      backgroundArrowColor: palette.neutral.neutral3,
    },
    modal: {
      backgroundColor: palette.neutral.neutral2,
      svgColor: palette.darken.darken1.darken1_base,
      svgDisabledColor: palette.darken.darken1.darken1_variant2,
      svgBackgroundColor: palette.neutral.none,
      svgBackgroundHoverColor: palette.darken.darken1.darken1_variant4,
      svgBackgroundActiveColor: palette.darken.darken1.darken1_variant3,
      shadow: palette.shadow.level_modal,
      borderCardsColor: palette.darken.darken1.darken1_variant1,
    },
    ui: {
      logoLinkColor: palette.darken.darken2.darken2_base,
      logoLinkHoverColor: palette.accent.accent1.accent1_base,
    },
    slider: {
      backgroundBulletColor: palette.darken.darken1.darken1_variant2,
      backgroundBulletActiveColor: palette.accent.accent1.accent1_base,
      backgroundButtonArrowColor: palette.neutral.neutral3,
      buttonArrowColor: palette.accent.accent1.accent1_base,
      hoverButtonArrowColor: palette.neutral.neutral1,
    },
    navbar: {
      logoColor: palette.darken.darken2.darken2_base,
      wrapperHeaderBackgroundColor: palette.neutral.neutral2,
      hoverColor: palette.accent.accent1.accent1_base,
      noHoverColor: palette.darken.darken2.darken2_base,
      textActiveLangColor: palette.darken.darken2.darken2_base,
      textNoActiveLangColor: palette.darken.darken2.darken2_variant1,
      svgColor: palette.darken.darken1.darken1_variant2,
      svgHoverColor: palette.darken.darken1.darken1_base,
      textLinkColor: palette.darken.darken1.darken1_variant2,
      textLinkHoverColor: palette.darken.darken1.darken1_base,
    },
    pgoressBar: {
      backgroundColor: palette.neutral.neutral3,
      aggregateColor: palette.darken.darken1.darken1_variant2,
      containerColor: palette.neutral.neutral4,
    },
    navLinks: {
      backgroundColor: palette.neutral.neutral3,
      hoverBackgroundColor: palette.darken.darken1.darken1_variant7,
      pressedBackgroundColor: palette.darken.darken1.darken1_variant8,
      borderColor: palette.darken.darken2.darken2_variant2,
      backgroundActiveColor: palette.accent.accent1.accent1_variant4,
    },
    footer: {
      wrapperHeaderBackgroundColor: palette.neutral.neutral2,
      linkSpanColor: palette.accent.accent1.accent1_base,
      linkSpanColorMedia1024: palette.darken.darken2.darken2_base,
      boxCopirightSpanColorMedia1024: palette.darken.darken2.darken2_variant1,
      linkTextColor: palette.darken.darken1.darken1_variant1,
      borderColor: palette.darken.darken2.darken2_variant2,
    },
    auth: {
      helpButtonColor: palette.accent.accent1.accent1_base,
      helpButtonHoverColor: palette.accent.accent1.accent1_variant2,
      helpButtonActiveColor: palette.accent.accent2,
      radioButtonColor: palette.accent.accent1.accent1_base,
      backgroundRegisterPage: palette.darken.darken2.darken2_variant2,
      backgroundRegisterContainerColor: palette.neutral.neutral2,
    },
    mainPage: {
      headingColor: palette.neutral.neutral1,
      titleColor: palette.darken.darken1.darken1_base,
      backgroundSectionTrendingColor: palette.neutral.neutral2,
      backgroundSectionCompaniesColor: palette.darken.darken2.darken2_variant2,
      backgroundSectionArticlesColor: palette.neutral.neutral2,
      backgroundSectionNewsColor: palette.darken.darken2.darken2_variant2,
      benefitHeadingMobileColor: palette.accent.accent1.accent1_base,
      benefitHeaderColorSmall: palette.accent.accent1.accent1_base,
      benefitHeaderColor: palette.darken.darken2.darken2_base,
      benefitBodyColorSmall: palette.darken.darken1.darken1_base,
      benefitBodyColor: palette.darken.darken1.darken1_variant1,
      benefitBorderColor: palette.neutral.neutral4,
    },
    user: {
      headingTextColor: palette.neutral.neutral1,
      backgroundPageColor: palette.darken.darken2.darken2_variant2,
      backgroundCardColor: palette.neutral.neutral2,
      borderColor: palette.neutral.neutral4,
      descriptionTextColor: palette.darken.darken1.darken1_variant1,
      iconColor: palette.accent.accent1.accent1_base,
      borderAvatar: palette.neutral.neutral2,
      borderCustomFieldData: palette.darken.darken1.darken1_variant2,
    },
    boxInformation: {
      info: {
        backgroundColor: palette.accent.accent1.accent1_variant5,
        borderColor: palette.accent.accent2,
      },
      warning: {
        backgroundColor: palette.info.info_warning.info_warning_variant3,
        borderColor: palette.info.info_warning.info_warning_variant2,
      },
      error: {
        backgroundColor: palette.info.info_errors.info_errors_variant3,
      },
      success: {
        backgroundColor: palette.info.info_success.info_success_variant2,
        borderColor: palette.info.info_success.info_success_variant1,
      },
    },
    responses: {
      filters: {
        backgroundColor: palette.neutral.neutral3,
      },
    },
  } as ITheme;
}
