name: 'Push tests'
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x

      - name: npm install
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Build smoke test
        run: npm run build
